In [1]:
from magpie import grasp as gt
import rtde_control
import rtde_receive
from magpie.motor_code import Motors
from magpie import ur5 as ur5
import time
import numpy as np
import copy
import magpie
from magpie.gripper import Gripper
from magpie import poses

In [ ]:
# dict of z-value vs z-offset
# 0.278: 0.1

In [30]:
tmat = np.array([[ 0.56880946,  0.02605214, -0.82205662, -0.0115574 ],
        [-0.71963393,  0.49970328, -0.48210335, -0.01657833],
        [ 0.39822456,  0.86580478,  0.30298396,  0.20080076],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

z_offset = 0.10
# z_offset += -0.045

# eye = np.eye(4)
# eye[2, 3] = -z_offset

# tmat = tmat @ eye
print(tmat)
aperture = 37
# z_offset = G.aperture_to_z(aperture)/1000.0

mmc = copy.deepcopy(tmat[:3, 3])
# grasp_pose = [mmc[1], -mmc[0], mmc[2]]
grasp_pose = mmc
tmat[:3, 3] = [0, 0, 0]
homePose = None


[[ 0.569  0.026 -0.822 -0.012]
 [-0.72   0.5   -0.482 -0.017]
 [ 0.398  0.866  0.303  0.201]
 [ 0.     0.     0.     1.   ]]


In [28]:
# move gripper to cartesian pos
# OR orient gripper in place
sleepRate = 1.5
# time.sleep(sleepRate)
ur = ur5.UR5_Interface()
try:
    ur.start()
    # homePose = ur.get_tcp_pose()
    homePose = ur.getPose()
    # print("Home pose: ", homePose)
    
    # in-place (or best attempt) re-orientation
    # currentPose = ur.getPose()
    # desiredPose = np.matmul(np.array(currentPose), tmat)
    # ur.moveL(desiredPose)
    # time.sleep(sleepRate * 1.2)

    ## move to cartesian pos
    gt.move_to_L(grasp_pose, ur, z_offset=z_offset)    
    print("Done moving to block")
    time.sleep(sleepRate * 1.2)
    ur.close_gripper()

    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[TxRxResult] There is no status packet!
[[ 0.016 -0.935 -0.355 -0.302]
 [-0.998 -0.035  0.048 -0.061]
 [-0.057  0.353 -0.934  0.098]
 [ 0.     0.     0.     1.   ]]
P_goal:
[-0.017  0.016 -0.09 ]
Done moving to block


In [29]:
# move home
ur = ur5.UR5_Interface()
try:
    ur.start()
    ur.open_gripper()
    # time.sleep(sleepRate)
    # homePose = np.array([[-0.024, -0.998, -0.062, -0.261],
    #                     [-0.999,  0.021,  0.035, -0.162],
    #                     [-0.033,  0.063, -0.997,  0.221],
    #                     [ 0.   ,  0.   ,  0.   ,  1.   ]])
    ur.moveL(homePose)
    # gt_home = ur.getPose()
    # print(np.array(gt_home))
    time.sleep(sleepRate * 1.1)
    ur.stop()
except Exception as e:
    ur.stop()

Succeeded to open the port
Succeeded to change the baudrate
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
