In [2]:
from magpie import grasp as gt
import rtde_control
import rtde_receive
from magpie.motor_code import Motors
from magpie import ur5 as ur5
import time
import numpy as np
import copy
import magpie
from magpie.gripper import Gripper

In [51]:
tmat = np.array([[ 0.94790874,  0.27621147, -0.15867025, -0.04556918],
        [-0.31809441,  0.84718496, -0.42555092,  0.00313948],
        [ 0.01688101,  0.45385556,  0.89091535,  0.25292859],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

aperture = 37
# z_offset = G.aperture_to_z(aperture)/1000.0

mmc = copy.deepcopy(tmat[:3, 3])
# grasp_pose = [mmc[1], -mmc[0], mmc[2]]
grasp_pose = mmc
tmat[:3, 3] = [0, 0, 0]
homePose = None
z_offset = 100/1000.0
z_offset += -0.00
z_offset

0.1

In [56]:
# move gripper to cartesian pos
# OR orient gripper in place
sleepRate = 1.5
# time.sleep(sleepRate)
ur = ur5.UR5_Interface()
try:
    ur.start()
    # homePose = ur.get_tcp_pose()
    homePose = ur.getPose()
    
    # in-place (or best attempt) re-orientation
    currentPose = ur.getPose()
    desiredPose = np.matmul(np.array(currentPose), tmat)
    ur.moveL(desiredPose)
    time.sleep(sleepRate * 1.2)

    ## move to cartesian pos
    gt.move_to_L(grasp_pose, ur, z_offset=z_offset)    
    print("Done moving to block")
    time.sleep(sleepRate * 1.2)

    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[[ 0.318 -0.942  0.104 -0.344]
 [-0.93  -0.289  0.225 -0.061]
 [-0.182 -0.168 -0.969  0.091]
 [ 0.     0.     0.     1.   ]]
P_goal:
[-0.002  0.076 -0.14 ]
Done moving to block


In [57]:
# move home
ur = ur5.UR5_Interface()
try:
    ur.start()
    # time.sleep(sleepRate)
    # homePose = np.array([[-0.024, -0.998, -0.062, -0.261],
    #                     [-0.999,  0.021,  0.035, -0.162],
    #                     [-0.033,  0.063, -0.997,  0.221],
    #                     [ 0.   ,  0.   ,  0.   ,  1.   ]])
    ur.moveL(homePose)
    # gt_home = ur.getPose()
    # print(np.array(gt_home))
    time.sleep(sleepRate * 1.1)
    ur.stop()
except Exception as e:
    ur.stop()

Succeeded to open the port
Succeeded to change the baudrate
