In [2]:
from magpie import grasp as gt
import rtde_control
import rtde_receive
from magpie.motor_code import Motors
from magpie import ur5 as ur5
import time
import numpy as np
import copy
import magpie
from magpie.gripper import Gripper
from magpie import poses

In [8]:
import importlib
importlib.reload(ur5)

<module 'magpie.ur5' from '/home/will/MAGPIE/magpie/ur5.py'>

In [32]:
# dict of z-value vs z-offset
# 0.278: 0.1

In [13]:
tmat = np.array([[ 4.04647815e-01,  8.32794272e-01, -3.77774862e-01,
         -1.88390845e-04],
        [-5.80105862e-01,  5.53112486e-01,  5.97949635e-01,
         -2.42551539e-02],
        [ 7.06921024e-01, -2.28096015e-02,  7.06924598e-01,
          3.87766416e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])

z_offset = 0.10
# z_offset += -0.045

# eye = np.eye(4)
# eye[2, 3] = -z_offset

# tmat = tmat @ eye
print(tmat)
aperture = 37
# z_offset = G.aperture_to_z(aperture)/1000.0

mmc = copy.deepcopy(tmat[:3, 3])
gripper_offset = [0.012, 0.006, 0.221] # x, y, z offset
grasp_pose = mmc - gripper_offset

# make identity matrix with grasp_pose as translation
tmat_offset = np.eye(4)
tmat_offset[:3, 3] = grasp_pose
print(tmat_offset)

# tmat[:3, 3] = [0, 0, 0]
homePose = None

[[ 4.046e-01  8.328e-01 -3.778e-01 -1.884e-04]
 [-5.801e-01  5.531e-01  5.979e-01 -2.426e-02]
 [ 7.069e-01 -2.281e-02  7.069e-01  3.878e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[ 1.     0.     0.    -0.012]
 [ 0.     1.     0.    -0.03 ]
 [ 0.     0.     1.     0.167]
 [ 0.     0.     0.     1.   ]]


In [14]:
# move gripper to cartesian pos
# OR orient gripper in place
sleepRate = 1.5
# time.sleep(sleepRate)
ur = ur5.UR5_Interface()
try:
    ur.start()
    # ur.open_gripper()
    homePose = ur.get_tcp_pose()
    # wristPose = ur.getPose()
    # wrist = np.array(wristPose)
    # # tmat[:3, 3] -= gripper_offset
    # print(wrist)
    # print(wrist @ tmat_offset)
    # desired_pose = wrist @ tmat_offset
    # ur.moveL(desired_pose)
    ur.move_tcp_cartesian(tmat)
    time.sleep(sleepRate * 1.2)# offset_pose = gt.get_world_frame(mmc, ur, -offset)
    # desiredPose = np.array(wristPose)
    # desiredPose[:3, 3] += offset_pose
    # print(desiredPose)
    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[[ 1.     0.     0.    -0.012]
 [ 0.     1.     0.    -0.03 ]
 [ 0.     0.     1.     0.167]
 [ 0.     0.     0.     1.   ]]
[[-0.997 -0.063  0.034 -0.18 ]
 [-0.07   0.965 -0.252 -0.34 ]
 [-0.017 -0.254 -0.967  0.248]
 [ 0.     0.     0.     1.   ]]


In [16]:
ur = ur5.UR5_Interface()
try:
    ur.start()
    ur.close_gripper()
    # ur.open_gripper()
    time.sleep(sleepRate)
    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate


In [17]:
# move home
ur = ur5.UR5_Interface()
try:
    ur.start()
    ur.open_gripper()
    # time.sleep(sleepRate)
    # homePose = np.array([[-0.024, -0.998, -0.062, -0.261],
    #                     [-0.999,  0.021,  0.035, -0.162],
    #                     [-0.033,  0.063, -0.997,  0.221],
    #                     [ 0.   ,  0.   ,  0.   ,  1.   ]])
    ur.moveL(homePose)
    # gt_home = ur.getPose()
    # print(np.array(gt_home))
    time.sleep(sleepRate * 1.1)
    ur.stop()
except Exception as e:
    ur.stop()

Succeeded to open the port
Succeeded to change the baudrate


In [4]:
# # move gripper to cartesian pos
# # OR orient gripper in place
# sleepRate = 1.5
# # time.sleep(sleepRate)
# ur = ur5.UR5_Interface()
# try:
#     ur.start()
#     homePose = ur.get_tcp_pose()
#     # homePose = ur.getPose()
#     # print("Home pose: ", homePose)
    
#     # in-place (or best attempt) re-orientation
#     # currentPose = ur.getPose()
#     # desiredPose = np.matmul(np.array(currentPose), tmat)
#     # ur.moveL(desiredPose)
#     # time.sleep(sleepRate * 1.2)

#     ## move to cartesian pos
#     gt.move_to_L(grasp_pose, ur, z_offset=z_offset)    
#     print("Done moving to block")
#     time.sleep(sleepRate * 1.2)
#     ur.close_gripper()

#     ur.stop()
# except Exception as e:
#     ur.stop()
#     raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[TxRxResult] Incorrect status packet!
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[[ 1.     0.004 -0.004  0.077]
 [ 0.004 -1.     0.022 -0.318]
 [-0.004 -0.022 -1.     0.089]
 [ 0.     0.     0.     1.   ]]
P_goal:
[-0.008  0.006 -0.09 ]
Done moving to block
