In [1]:
from magpie import grasp as gt
import rtde_control
import rtde_receive
from magpie.motor_code import Motors
from magpie import ur5 as ur5
import time
import numpy as np
import copy
import magpie
from magpie.gripper import Gripper
from magpie import poses

In [32]:
# dict of z-value vs z-offset
# 0.278: 0.1

In [9]:
tmat = np.array([[ 0.09428926,  0.93582841,  0.33960966, -0.00428812],
        [-0.44995814,  0.34435828, -0.82398728, -0.01148746],
        [-0.88805811, -0.07511698,  0.4535529 ,  0.17063418],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

z_offset = 0.10
# z_offset += -0.045

# eye = np.eye(4)
# eye[2, 3] = -z_offset

# tmat = tmat @ eye
print(tmat)
aperture = 37
# z_offset = G.aperture_to_z(aperture)/1000.0

mmc = copy.deepcopy(tmat[:3, 3])
# grasp_pose = [mmc[1], -mmc[0], mmc[2]]
grasp_pose = mmc
# tmat[:3, 3] = [0, 0, 0]
homePose = None


[[ 0.094  0.936  0.34  -0.004]
 [-0.45   0.344 -0.824 -0.011]
 [-0.888 -0.075  0.454  0.171]
 [ 0.     0.     0.     1.   ]]


In [10]:
offset = (309.63 - 195.0)/1000
tmat[2, 3] += offset
print(tmat)

[[ 0.094  0.936  0.34  -0.004]
 [-0.45   0.344 -0.824 -0.011]
 [-0.888 -0.075  0.454  0.285]
 [ 0.     0.     0.     1.   ]]


In [14]:
# move gripper to cartesian pos
# OR orient gripper in place
sleepRate = 1.5
# time.sleep(sleepRate)
ur = ur5.UR5_Interface()
try:
    ur.start()
    # homePose = ur.get_tcp_pose()
    wristPose = ur.getPose()
    wrist = np.array(wristPose)
    print(wrist)
    print(wrist @ tmat)
    offset_pose = gt.get_world_frame(mmc, ur, -offset)
    desiredPose = np.array(wristPose)
    desiredPose[:3, 3] += offset_pose
    print(desiredPose)
    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[[ 1.     0.004 -0.005  0.078]
 [ 0.004 -1.     0.022 -0.324]
 [-0.004 -0.022 -1.     0.31 ]
 [ 0.     0.     0.     1.   ]]
[[ 0.096  0.938  0.334  0.073]
 [ 0.431 -0.342  0.835 -0.306]
 [ 0.897  0.063 -0.437  0.025]
 [ 0.     0.     0.     1.   ]]
[[ 1.     0.004 -0.005  0.078]
 [ 0.004 -1.     0.022 -0.324]
 [-0.004 -0.022 -1.     0.31 ]
 [ 0.     0.     0.     1.   ]]
P_goal:
[-0.006  0.018 -0.285]
[[ 1.     0.004 -0.005  0.073]
 [ 0.004 -1.     0.022 -0.306]
 [-0.004 -0.022 -1.     0.025]
 [ 0.     0.     0.     1.   ]]


In [4]:
# # move gripper to cartesian pos
# # OR orient gripper in place
# sleepRate = 1.5
# # time.sleep(sleepRate)
# ur = ur5.UR5_Interface()
# try:
#     ur.start()
#     homePose = ur.get_tcp_pose()
#     # homePose = ur.getPose()
#     # print("Home pose: ", homePose)
    
#     # in-place (or best attempt) re-orientation
#     # currentPose = ur.getPose()
#     # desiredPose = np.matmul(np.array(currentPose), tmat)
#     # ur.moveL(desiredPose)
#     # time.sleep(sleepRate * 1.2)

#     ## move to cartesian pos
#     gt.move_to_L(grasp_pose, ur, z_offset=z_offset)    
#     print("Done moving to block")
#     time.sleep(sleepRate * 1.2)
#     ur.close_gripper()

#     ur.stop()
# except Exception as e:
#     ur.stop()
#     raise(e)

Succeeded to open the port
Succeeded to change the baudrate
[TxRxResult] Incorrect status packet!
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[TxRxResult] There is no status packet!
[[ 1.     0.004 -0.004  0.077]
 [ 0.004 -1.     0.022 -0.318]
 [-0.004 -0.022 -1.     0.089]
 [ 0.     0.     0.     1.   ]]
P_goal:
[-0.008  0.006 -0.09 ]
Done moving to block


In [5]:
# # move home
# ur = ur5.UR5_Interface()
# try:
#     ur.start()
#     ur.open_gripper()
#     # time.sleep(sleepRate)
#     # homePose = np.array([[-0.024, -0.998, -0.062, -0.261],
#     #                     [-0.999,  0.021,  0.035, -0.162],
#     #                     [-0.033,  0.063, -0.997,  0.221],
#     #                     [ 0.   ,  0.   ,  0.   ,  1.   ]])
#     ur.moveL(homePose)
#     # gt_home = ur.getPose()
#     # print(np.array(gt_home))
#     time.sleep(sleepRate * 1.1)
#     ur.stop()
# except Exception as e:
#     ur.stop()

Succeeded to open the port
Succeeded to change the baudrate
