In [3]:
from magpie import grasp as gt
import rtde_control
import rtde_receive
from magpie.motor_code import Motors
from magpie import ur5 as ur5
import time
import numpy as np
import copy

In [4]:
import importlib
importlib.reload(gt)
importlib.reload(ur5)

<module 'magpie.ur5' from '/home/will/MAGPIE/magpie/ur5.py'>

In [26]:
# tmat = np.array([[ 0.91574736, -0.35602909,  0.18614527, -0.02848649],
#        [-0.40073104, -0.77640133,  0.48643151,  0.14332736],
#        [ 0.02866033,  0.52004256,  0.85365937,  0.33750796],
#        [ 0.        ,  0.        ,  0.        ,  1.        ]])

tmat = np.array([[ 0.9401755 , -0.34018102, -0.01862539, -0.09287199],
       [ 0.34020501,  0.94034924, -0.00196259,  0.0074593 ],
       [ 0.018182  , -0.00449127,  0.99982461,  0.25738291],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

z_offset = 0.103

mmc = copy.deepcopy(tmat[:3, 3])
# grasp_pose = [mmc[1], -mmc[0], mmc[2]]
grasp_pose = mmc
tmat[:3, 3] = [0, 0, 0]
homePose = None

In [24]:
# orient gripper in place OR move gripper to cartesian pos
sleepRate = 1.5
ur = ur5.UR5_Interface()
try:
    ur.start()
    # homePose = ur.get_tcp_pose()
    homePose = ur.getPose()
    currentPose = ur.getPose()
    desiredPose = np.matmul(np.array(currentPose), tmat)
    print("Desired Pose: ", desiredPose)
    # in-place (or best attempt) re-orientation
    # ur.moveL(desiredPose)
    ## move to cartesian pos
    gt.move_to(grasp_pose, ur, z_offset=0.093)    
    print("Done moving to block")
    time.sleep(sleepRate)
    time.sleep(sleepRate)
    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
Moving speed of dxl ID: 1 set to 100 
Moving speed of dxl ID: 2 set to 100 
Desired Pose:  [[-0.981 -0.036 -0.19  -0.046]
 [ 0.086  0.798 -0.597 -0.475]
 [ 0.173 -0.602 -0.78   0.133]
 [ 0.     0.     0.     1.   ]]
[[ 9.999e-01  7.647e-03 -9.051e-03 -4.576e-02]
 [ 7.645e-03 -1.000e+00 -2.816e-04 -4.750e-01]
 [-9.052e-03  2.124e-04 -1.000e+00  1.327e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
P_goal:
[ 0.062  0.009 -0.169]
Done moving to block


In [25]:
# move home
ur = ur5.UR5_Interface()
try:
    ur.start()
    # time.sleep(sleepRate)
    ur.moveL(homePose)
    time.sleep(sleepRate)
    ur.stop()
except Exception as e:
    ur.stop()

Succeeded to open the port
Succeeded to change the baudrate
Moving speed of dxl ID: 1 set to 100 
Moving speed of dxl ID: 2 set to 100 


In [27]:
# orient and move gripper to cartesian pos
sleepRate = 1.5
ur = ur5.UR5_Interface()
try:
    servoPort = "/dev/ttyACM0"
    ur.start()
    time.sleep(sleepRate)
    homePose = ur.get_tcp_pose()
    dX,dY,dZ = gt.get_world_frame(grasp_pose, ur, z_offset=0.086)
    

    '''
    stopping point 2/15:
    this works so far
    take home pos
    add translation on the gripper frame to the goal x, y
    apply tmat to the goal
    move to goal (translates on x, y and orients at the same time)
    ## does this address the fact that orientation is not achievable in standstill?

    then: take orig Z (from original gripper frame): [0, 0, dZ]
    transform by tmat (the current orientation of the gripper)
    add transformed dZ to the goal position
    move
    works!
    '''
    goal1 = copy.deepcopy(homePose)
    goal1 = np.array(goal1)
    goal1[:3, 3] += [dX, dY, 0]
    goal1 = np.array(goal1) @ tmat
    ur.moveL(goal1)
    time.sleep(sleepRate)

    # todo: take currentPose and validate orientation?
    goal2 = goal1
    z_off = -0.00
    posd = [0, 0, dZ - z_off] @ tmat[:3, :3]
    # posd = [0, 0, dZ - z_off]
    goal2 = np.array(goal2)
    goal2[:3, 3] += posd
    ur.moveL(goal2)
    time.sleep(sleepRate)
    '''
    end of working section
    '''
    ur.stop()
except Exception as e:
    ur.stop()
    raise(e)

Succeeded to open the port
Succeeded to change the baudrate
Moving speed of dxl ID: 1 set to 100 
Moving speed of dxl ID: 2 set to 100 
[[ 9.999e-01  7.743e-03 -9.016e-03 -4.573e-02]
 [ 7.741e-03 -1.000e+00 -2.933e-04 -4.750e-01]
 [-9.018e-03  2.234e-04 -1.000e+00  1.327e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
P_goal:
[-0.094 -0.008 -0.154]


In [5]:
# orient and move gripper to cartesian pos
sleepRate = 1.5
ur = ur5.UR5_Interface()
try:
    servoPort = "/dev/ttyACM0"
    gripperController = Motors(servoPort)
    gripperController.torquelimit(600) # used to be 600
    gripperController.speedlimit(100)
    ur.start()
    ur.gripper = gripperController
    time.sleep(sleepRate)

    homePose = ur.get_tcp_pose()
    dX,dY,dZ = gt.get_world_frame(grasp_pose, ur)
    '''
    stopping point 2/15:
    this works so far
    take home pos
    add translation on the gripper frame to the goal x, y
    apply tmat to the goal
    move to goal (translates on x, y and orients at the same time)
    ## does this address the fact that orientation is not achievable in standstill?

    then: take orig Z (from original gripper frame): [0, 0, dZ]
    transform by tmat (the current orientation of the gripper)
    add transformed dZ to the goal position
    move
    works!
    '''
    goal1 = copy.deepcopy(homePose)
    goal1 = np.array(goal1)
    goal1[:3, 3] += [dX, dY, 0]
    goal1 = np.array(goal1) @ tmat
    ur.moveL(goal1)
    time.sleep(sleepRate)

    # todo: take currentPose and validate orientation?
    goal2 = goal1
    z_off = -0.00
    posd = [0, 0, dZ - z_off] @ tmat[:3, :3]
    goal2 = np.array(goal2)
    goal2[:3, 3] += posd
    ur.moveL(goal2)
    time.sleep(sleepRate)
    '''
    end of working section
    '''

    print("Done moving to block")
    # ur.closeGripper(9) 
    time.sleep(sleepRate)
    # gt.moveBackFromObj(homePose, ur)
    # gt.grabStrat1(grasp_pose)
    ur.moveL(homePose)
    time.sleep(sleepRate)
    # ur.openGripper()
    ur.stop()
except Exception as e:
    gripperController.openGripper()
    gripperController.disconnect()
    ur.stop()
    raise(e)

UR5 Interface Established


AttributeError: 'NoneType' object has no attribute 'moveL'