In [1]:
import openai
import os
import sys
import termcolor
import json
import tensorflow as tf
import codecs
sys.path.append("../")
from magpie.prompt_planner.prompts import mp_prompt_thinker_coder_muk as mptc
from magpie.prompt_planner.prompts import dg_command_enumerator as dgce
from magpie.prompt_planner import conversation
from magpie.prompt_planner import confirmation_safe_executor
from magpie.prompt_planner import task_configs
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds
import rlds
API_KEY = os.environ['CORRELL_API_KEY']

2024-09-12 13:43:38.110936: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-12 13:43:38.110961: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-12 13:43:38.111844: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-12 13:43:38.116865: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-12 13:43:38.803301: W tensorflow/compiler/tf2

In [2]:
RESPONSE = '''

import sys
sys.path.append('../../')
sys.path.append('../')


def reset_reward(*args, **kwargs):
  pass


def execute_plan(*args, **kwargs):
  pass



from magpie.gripper import Gripper  # Import the gripper class
import numpy as np  # Import numpy for numerical operations

G = Gripper()  # Create a gripper object

# Since this is a new grasp, reset parameters to default to ensure no previous settings interfere.
G.reset_parameters()

# Set the goal aperture to 60.0 mm for the rubber duck which is small and lightweight.
goal_aperture = 28.0
# This is a complete grasp, so the gripper will not open after attempting the grasp.
complete_grasp = True
# Initial force calculation based on object weight and friction coefficient.
initial_force = (50 * 9.81) / (0.8 * 1000)  # 0.6125 N
# Additional closure if the gripper slips.
additional_closure = 2.0
# Additional force increase if the gripper slips, calculated as product of spring constant and additional closure.
additional_force = np.max([0.01, additional_closure * 100 * 0.0001])  # 0.02 N

# Move quickly to a safe aperture that is wider than the goal aperture to prepare for grasping.
G.set_goal_aperture(goal_aperture + additional_closure * 2, finger='both', record_load=False)

# Set compliance to allow a small margin of error in positioning and moderate flexibility.
G.set_compliance(1, 3, finger='both')

# Set the initial force to be applied by the gripper.
G.set_force(initial_force, 'both')

# Execute the grasp with the specified parameters.
G.deligrasp(goal_aperture, initial_force, additional_closure, additional_force, complete_grasp)

# Prediction of gripper's state after the commands:
# The gripper will attempt to close to the goal aperture of 60.0 mm, applying an initial force of 0.6125 N.
# If slipping is detected, it will close an additional 2.0 mm and increase the force by 0.02 N.
# Since the grasp is complete, the gripper will maintain its position and force after the adjustment.
'''

In [3]:
PROMPT_TYPE = 'thinker_coder'
TASK_CONFIG = task_configs.ALL_TASKS["magpie"]
openai.api_key = API_KEY
safe_executor = confirmation_safe_executor.ConfirmationSafeExecutor(
    skip_confirmation=True,
    local_execute=True)
PROMPT = TASK_CONFIG.prompts[PROMPT_TYPE]
PROMPT_MODEL = PROMPT(
    None, executor=safe_executor
)
pm = PROMPT_MODEL

In [4]:
stdout = pm.code_executor(RESPONSE)


ABOUT TO EXECUTE TC MUK 
 

import sys
sys.path.append('../../')
sys.path.append('../')


def reset_reward(*args, **kwargs):
  pass


def execute_plan(*args, **kwargs):
  pass



from magpie.gripper import Gripper  # Import the gripper class
import numpy as np  # Import numpy for numerical operations

G = Gripper()  # Create a gripper object

# Since this is a new grasp, reset parameters to default to ensure no previous settings interfere.
G.reset_parameters()

# Set the goal aperture to 60.0 mm for the rubber duck which is small and lightweight.
goal_aperture = 28.0
# This is a complete grasp, so the gripper will not open after attempting the grasp.
complete_grasp = True
# Initial force calculation based on object weight and friction coefficient.
initial_force = (50 * 9.81) / (0.8 * 1000)  # 0.6125 N
# Additional closure if the gripper slips.
additional_closure = 2.0
# Additional force increase if the gripper slips, calculated as product of spring constant and additional closure.
addi

In [5]:
from magpie import realsense_wrapper
import asyncio
from concurrent.futures import ThreadPoolExecutor

rsc = realsense_wrapper.RealSense(fps=15) # 10 Hz
rsc.initConnection()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [6]:
async def execute_grasp_and_record_images(code_executor, code, camera, path="test_datasets/"):
    camera.begin_record(filepath=f"{path}")
    loop = asyncio.get_event_loop()
    with ThreadPoolExecutor() as pool:
        grasp_log = await loop.run_in_executor(pool, code_executor, code)
    print(grasp_log)
    await camera.stop_record()
    return grasp_log

gl = await execute_grasp_and_record_images(pm.code_executor, RESPONSE, rsc)

Recording Started
ABOUT TO EXECUTE TC MUK 
 

import sys
sys.path.append('../../')
sys.path.append('../')


def reset_reward(*args, **kwargs):
  pass


def execute_plan(*args, **kwargs):
  pass



from magpie.gripper import Gripper  # Import the gripper class
import numpy as np  # Import numpy for numerical operations

G = Gripper()  # Create a gripper object

# Since this is a new grasp, reset parameters to default to ensure no previous settings interfere.
G.reset_parameters()

# Set the goal aperture to 60.0 mm for the rubber duck which is small and lightweight.
goal_aperture = 28.0
# This is a complete grasp, so the gripper will not open after attempting the grasp.
complete_grasp = True
# Initial force calculation based on object weight and friction coefficient.
initial_force = (50 * 9.81) / (0.8 * 1000)  # 0.6125 N
# Additional closure if the gripper slips.
additional_closure = 2.0
# Additional force increase if the gripper slips, calculated as product of spring constant and additi

In [7]:
gl

"Succeeded to open the port\nSucceeded to change the baudrate\n[{'timestamp': 1726170338.7195966, 'aperture': 29.88116121050554, 'gripper_vel': 0, 'contact_force': 0.3940891324999999, 'contact_force_l': 0.6564318399999998, 'contact_force_r': 0.131746425, 'applied_force': 0.613125, 'k': 0}, {'timestamp': 1726170338.8986886, 'aperture': 27.80905302236379, 'gripper_vel': 11.570081262937466, 'contact_force': 0.18903639756944446, 'contact_force_l': 0.19850390625, 'contact_force_r': 0.1795688888888889, 'applied_force': 0.633125, 'k': 391.7038672604646}, {'timestamp': 1726170339.0325692, 'aperture': 26.197152866097774, 'gripper_vel': 12.039832304655768, 'contact_force': 0.09276545, 'contact_force_l': 0.0915417, 'contact_force_r': 0.0939892, 'applied_force': 0.6531250000000001, 'k': 149.52864335108742}, {'timestamp': 1726170339.2249682, 'aperture': 23.89524555635873, 'gripper_vel': 11.964235838394641, 'contact_force': 0.10258730946745565, 'contact_force_l': 0.12343691893491127, 'contact_force_

In [8]:
import ast
import json

def log_grasp(grasp_log, path="test_grasp_json/grasp_log.json"):
    # list of dictionaries to json
    # get content after last newline of stdout
    sep = grasp_log.split('\n')
    gl = np.array(ast.literal_eval(sep[-2]))
    # write list of dicts to json
    with open(path, 'w') as f:
        f.write(json.dumps(gl.tolist()))

log_grasp(gl)

In [6]:
import ast
from server_util import log_grasp

# get content after last newline of stdout
sep = stdout.split('\n')
gl = np.array(ast.literal_eval(sep[-2]))
gl

array([{'timestamp': 1719875813.4930115, 'aperture': 30.341767066923943, 'gripper_vel': 0, 'contact_force': 0.04314361157024794, 'contact_force_l': 0.02131251900826446, 'contact_force_r': 0.06497470413223141, 'applied_force': 0.613125, 'k': 0},
       {'timestamp': 1719875813.6686172, 'aperture': 27.80900566920235, 'gripper_vel': 14.422996129911139, 'contact_force': 0.09267703125, 'contact_force_l': 0.06514265625, 'contact_force_r': 0.12021140625, 'applied_force': 0.613125, 'k': 234.7288072054378},
       {'timestamp': 1719875813.845577, 'aperture': 26.427462589527615, 'gripper_vel': 7.807103343943882, 'contact_force': 0.15068225000000002, 'contact_force_l': 0.2098228, 'contact_force_r': 0.0915417, 'applied_force': 0.613125, 'k': 208.17401971731837},
       {'timestamp': 1719875814.0502427, 'aperture': 23.89524555635873, 'gripper_vel': 12.372456730412942, 'contact_force': 0.10410272857142858, 'contact_force_l': 0.11386672857142859, 'contact_force_r': 0.09433872857142858, 'applied_force

In [8]:
# write gl to json
import json
with open('robot_logs/grasp_test.json', 'w') as f:
    f.write(json.dumps(gl.tolist()))

In [9]:
import codecs
import json

def log_to_rlds():
    '''
    combine 3 logs:
    1. move (csv)
    2. grasp_log (json)
    3. home (csv)
    into one tfds in rlds format
    rlds: https://github.com/google-research/rlds?tab=readme-ov-file#load-with-tfds
    '''
    # list of dictionaries to tfds
    # https://stackoverflow.com/questions/68567630/converting-a-list-of-dictionaries-to-a-tf-dataset

    # load csv to pd df
    home = pd.read_csv("robot_logs/test.csv")
    move = pd.read_csv("robot_logs/test.csv")

    # extract timestamp columns and actual_qd columns from actual_qd_0 to actual_qd_5
    home = home[['timestamp', 'actual_qd_0', 'actual_qd_1', 'actual_qd_2', 'actual_qd_3', 'actual_qd_4', 'actual_qd_5']]
    move = move[['timestamp', 'actual_qd_0', 'actual_qd_1', 'actual_qd_2', 'actual_qd_3', 'actual_qd_4', 'actual_qd_5']]

    # load json
    path = "robot_logs/grasp_log.json"
    obj_text = codecs.open(path, 'r', encoding='utf-8').read()
    gl = np.array(json.loads(obj_text))
    grasp_log = pd.DataFrame(gl.tolist()) # convert to pd df
    # keep only timestamp, aperture, gripper_vel, and contact_force cols, add actual_qd columns from actual_qd_0 to actual_qd_6 from the last row of move to grasp_log

    grasp_log = (grasp_log[['timestamp']] + 
                 move.iloc[-1][['actual_qd_0', 'actual_qd_1', 'actual_qd_2', 'actual_qd_3', 'actual_qd_4', 'actual_qd_5']] +
                 grasp_log[['aperture', 'gripper_vel', 'contact_force']])
    
    # add columns to move and home dfs, zeroed out
    move['aperture'] = 0
    move['gripper_vel'] = 0
    move['contact_force'] = 0
    home['aperture'] = 0
    home['gripper_vel'] = 0
    home['contact_force'] = 0


    # get initial values, iteratively subtract 0.1s from ti and assign to to move timestamps, from last to first
    ti = gl[0]['timestamp']
    ai = gl[0]['aperture']

    for i in np.arange(len(move)-1, -1, -1):
        # iterate backwards through move timestamps
        ti -= 0.1
        move.loc[i, 'timestamp'] = ti
        move.loc[i, 'aperture'] = ai

    # get last timestamp tf, iteratively add 0.1s to tf and assign to to home timestamps, from first to last
    tf = gl[-1]['timestamp']
    af = gl[-1]['aperture']
    cf = gl[-1]['contact_force']

    for i in np.arange(len(home)):
        # iterate forwards through home timestamps
        tf += 0.1
        home.loc[i, 'timestamp'] = tf
        home.loc[i, 'aperture'] = af
        home.loc[i, 'contact_force'] = cf

    # combine dataframes vertically
    df = pd.concat([move, grasp_log, home], axis=0)
    return df, grasp_log, home, move

df, gl, h, m = log_to_rlds()
df


/tmp/ipykernel_60187/2628835632.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '30.341767066923943' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  move.loc[i, 'aperture'] = ai
/tmp/ipykernel_60187/2628835632.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '15.864835708441316' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  home.loc[i, 'aperture'] = af
/tmp/ipykernel_60187/2628835632.py:64: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.36463737500000004' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  home.loc[i, 'contact_force'] = cf


timestamp  actual_qd_0  actual_qd_1  actual_qd_2  actual_qd_3  \
0    1.719876e+09     0.001078    -2.469845     2.349459    -1.955513   
1    1.719876e+09     0.001066    -2.469773     2.349483    -1.955452   
2    1.719876e+09     0.001006    -2.469785     2.349447    -1.955489   
3    1.719876e+09     0.001054    -2.469833     2.349519    -1.955452   
4    1.719876e+09     0.001054    -2.469821     2.349519    -1.955525   
..            ...          ...          ...          ...          ...   
197  1.719876e+09    -0.017217    -2.074527     2.649140    -2.651230   
198  1.719876e+09    -0.017205    -2.074479     2.649140    -2.651218   
199  1.719876e+09    -0.017229    -2.074467     2.649104    -2.651242   
200  1.719876e+09    -0.017229    -2.074467     2.649164    -2.651230   
201  1.719876e+09    -0.017229    -2.074479     2.649140    -2.651230   

     actual_qd_4  actual_qd_5   aperture  gripper_vel  contact_force  
0      -1.612564    -3.034139  30.341767          0.0       0.000000  
1      -1.612540    -3.034175  30.341767          0.0       0.000000  
2      -1.612564    -3.034163  30.341767          0.0       0.000000  
3      -1.612564    -3.034163  30.341767          0.0       0.000000  
4      -1.612540    -3.034139  30.341767          0.0       0.000000  
..           ...          ...        ...          ...            ...  
197    -1.607235    -3.047362  15.864836          0.0       0.364637  
198    -1.607187    -3.047386  15.864836          0.0       0.364637  
199    -1.607211    -3.047374  15.864836          0.0       0.364637  
200    -1.607235    -3.047386  15.864836          0.0       0.364637  
201    -1.607175    -3.047398  15.864836          0.0       0.364637  

[415 rows x 10 columns]

In [41]:
# write df to csv
df.to_csv('robot_logs/combined_df.csv', index=False)

# pd df to tfds 

In [44]:
tfds = tf.data.Dataset.from_tensor_slices(df.to_dict(orient='list'))

# pd df direct to rlds

In [10]:
# !pip install rlds
import rlds

episode_steps = df.to_dict(orient='records')

# Convert list of dictionaries to RLDS episode
episode = {
    'steps':[{
        'observation': {
            'timestamp': step['timestamp'],
            'actual_qd': [
                step['actual_qd_0'],
                step['actual_qd_1'],
                step['actual_qd_2'],
                step['actual_qd_3'],
                step['actual_qd_4'],
                step['actual_qd_5']
            ],
            'aperture': step['aperture'],
            'gripper_vel': step['gripper_vel'],
            'contact_force': step['contact_force'],
            'image': np.zeros([64, 64, 3])
        },
        'action': 1,  # Placeholder, assuming no action data is available
        'reward': 0,  # Placeholder, assuming no reward data is available
        'is_terminal': False  # Placeholder, assuming steps are not terminal
    } for step in episode_steps]
}

# Print the RLDS episode
print(episode)


{'steps': [{'observation': {'timestamp': 1719875793.2930307, 'actual_qd': [0.001078, -2.469845, 2.349459, -1.955513, -1.612564, -3.034139], 'aperture': 30.341767066923943, 'gripper_vel': 0.0, 'contact_force': 0.0, 'image': array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
       

In [13]:
# Convert the episode to a list of tuples
steps = [
    (
        step['observation'],  # observation
        step['action'],       # action
        step['reward'],       # reward
        step['is_terminal']   # is_terminal
    )
    for step in episode['steps']
]

# Generator function
def generator():
    for step in steps:
        yield step

# Define the dataset types and shapes
output_types = (
    {
        'timestamp': tf.float32,
        # actual_qd is a 6-dimensional vector
        'actual_qd': tf.float32,
        'aperture': tf.float32,
        'gripper_vel': tf.float32,
        'contact_force': tf.float32,
        'image': tf.uint8
    },
    tf.float32,  # action
    tf.float32,  # reward
    tf.bool      # is_terminal
)

output_shapes = (
    {
        'timestamp': tf.TensorShape([]),
        'actual_qd': tf.TensorShape([6]),
        'aperture': tf.TensorShape([]),
        'gripper_vel': tf.TensorShape([]),
        'contact_force': tf.TensorShape([]),
        'image': tf.TensorShape([64, 64, 3])
    },
    tf.TensorShape([]),  # action
    tf.TensorShape([]),  # reward
    tf.TensorShape([])   # is_terminal
)

# Create the tf.data.Dataset
dataset = tf.data.Dataset.from_generator(
    generator,
    output_types=output_types,
    output_shapes=output_shapes
)

# Print the dataset
for element in dataset:
    print(element)



2024-07-01 17:28:30.984582: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-01 17:28:30.985239: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-01 17:28:30.985686: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

InternalError: cudaSetDevice() on GPU:0 failed. Status: CUDA-capable device(s) is/are busy or unavailable

In [62]:
import tensorflow as tf
rl = tf.data.Dataset.load("robot_logs/episode_2024_07_01_18_02_32_id-0")
metadata = {
    'timestamp': tf.float32,
    'actual_qd': tf.float32,
    'aperture': tf.float32,
    'gripper_vel': tf.float32,
    'contact_force': tf.float32,
    'image': tf.uint8
}

In [65]:
for elem in rl:
    print(elem)

({'timestamp': <tf.Tensor: shape=(), dtype=float32, numpy=1719878500.0>, 'aperture': <tf.Tensor: shape=(), dtype=float32, numpy=51.68621>, 'contact_force': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'actual_qd': <tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0.,  0., -0.,  0.,  0.,  0.], dtype=float32)>, 'image': <tf.Tensor: shape=(480, 640, 3), dtype=uint8, numpy=
array([[[ 24,  45,  51],
        [ 23,  45,  48],
        [ 23,  45,  46],
        ...,
        [ 29,  47,  51],
        [ 28,  45,  50],
        [ 28,  45,  50]],

       [[ 24,  45,  51],
        [ 25,  47,  51],
        [ 25,  47,  48],
        ...,
        [ 26,  45,  49],
        [ 24,  43,  47],
        [ 24,  43,  47]],

       [[ 22,  44,  52],
        [ 23,  46,  51],
        [ 23,  47,  49],
        ...,
        [ 27,  46,  49],
        [ 27,  46,  50],
        [ 26,  45,  49]],

       ...,

       [[ 43,  45,  50],
        [ 43,  46,  50],
        [ 39,  46,  48],
        ...,
        [131, 138, 141],

In [61]:
tfds.builder_from_directory("robot_logs/episode_2024_07_01_18_02_32_id-0")

FileNotFoundError: Could not load dataset info from robot_logs/episode_2024_07_01_18_02_32_id-0/dataset_info.json

In [63]:
rl

<_LoadDataset element_spec=({'timestamp': TensorSpec(shape=(), dtype=tf.float32, name=None), 'aperture': TensorSpec(shape=(), dtype=tf.float32, name=None), 'contact_force': TensorSpec(shape=(), dtype=tf.float32, name=None), 'actual_qd': TensorSpec(shape=(6,), dtype=tf.float32, name=None), 'image': TensorSpec(shape=(480, 640, 3), dtype=tf.uint8, name=None), 'gripper_vel': TensorSpec(shape=(), dtype=tf.float32, name=None)}, TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.bool, name=None))>

In [9]:
import codecs
obj_text = codecs.open(path, 'r', encoding='utf-8').read()
b_new = json.loads(obj_text)
a_new = np.array(b_new)

In [2]:
task_configs.ALL_TASKS

{'magpie': TaskConfig(client=None, prompts={'thinker_coder': <class 'magpie.prompt_planner.prompts.mp_prompt_thinker_coder_muk.PromptThinkerCoder'>, 'thinker_coder_phys': <class 'magpie.prompt_planner.prompts.mp_prompt_tc_phys.PromptThinkerCoderPhys'>, 'thinker_coder_vision': <class 'magpie.prompt_planner.prompts.mp_prompt_tc_vision.PromptThinkerCoderVision'>, 'thinker_coder_vision_phys': <class 'magpie.prompt_planner.prompts.mp_prompt_tc_vision_phys.PromptThinkerCoderVisionPhys'>}),
 'system': TaskConfig(client=None, prompts={'system_executor': <class 'magpie.prompt_planner.prompts.dg_system_executor.PromptSystemExecutor'>}),
 'command_enumerator': TaskConfig(client=None, prompts={'command_enumerator': <class 'magpie.prompt_planner.prompts.dg_command_enumerator.PromptCommandEnumerator'>})}

In [3]:
tc = task_configs.ALL_TASKS['command_enumerator']
prompt = tc.prompts['command_enumerator']
MODEL = "gpt-3.5-turbo"
# MODEL = "gpt-4-turbo"
safe_executor = confirmation_safe_executor.ConfirmationSafeExecutor()
openai.api_key = API_KEY


In [8]:
# user_command = "gently pick the five largest and ripest tomatos and three small avocados"
# try:
#     prompt_model = prompt(
#         None, executor=safe_executor
#     )
#     conv = conversation.Conversation(prompt_model, MODEL)
#     # while True:
#       # user_command = input(termcolor.colored("User: ", "red", attrs=["bold"]))
#     try:
#       response = conv.send_command(user_command)
#       print(termcolor.colored("Magpie: ", "green", attrs=["bold"]) + response + "\n")
#     except Exception as e:  # pylint: disable=broad-exception-caught
#       print("Planning failed, try something else... " + str(e) + "\n")
#       # continue
    
#       # try:
#       #   prompt_model.code_executor(response)
#       # except Exception as e:  # pylint: disable=broad-exception-caught
#       #   print("Execution failed, try something else... " + str(e) + "\n")

# except Exception as e:
#     print(e)
#     prompt_model = None

LLM0 queried
[start of enumeration]
{'objects': ['tomato', 'avocado'],
'object_qualities': {'tomato': ['ripe', 'large'], 'avocado': ['small']},
'manipulation': 'pick',
'manipulation_qualities': ['gently']}
[end of enumeration]

processing response
processing command enumeration
LLM0 processed response: {'objects': ['tomato', 'avocado'],
'object_qualities': {'tomato': ['ripe', 'large'], 'avocado': ['small']},
'manipulation': 'pick',
'manipulation_qualities': ['gently']}
Magpie: {'objects': ['tomato', 'avocado'],
'object_qualities': {'tomato': ['ripe', 'large'], 'avocado': ['small']},
'manipulation': 'pick',
'manipulation_qualities': ['gently']}



In [11]:
import ast
ast.literal_eval(response)

{'objects': ['tomato', 'avocado'],
 'object_qualities': {'tomato': ['ripe', 'large'], 'avocado': ['small']},
 'manipulation': 'pick',
 'manipulation_qualities': ['gently']}

In [8]:
response = """
[start of enumeration]
1. Objects: ["avocados"]
2. Object Qualities: {"avocados": ["large"]}
3. Manipulation: "pick"
4. Manipulation Qualities: ["gently", "ignore irrelevant options"]
[end of enumeration]
"""

In [9]:
import re
import ast
import json
command_enumeration = (
    re.split(
        "end of enumeration",
        re.split("start of enumeration", response, flags=re.IGNORECASE)[
            1
        ],
        flags=re.IGNORECASE,
    )[0]
    .strip("[")
    .strip("]")
    .strip()
    .strip("```")
)


In [10]:
command_enumeration

'1. Objects: ["avocados"]\n2. Object Qualities: {"avocados": ["large"]}\n3. Manipulation: "pick"\n4. Manipulation Qualities: ["gently", "ignore irrelevant options"]'

In [11]:
# get object(s) as list from command_enumeration, try to use ast.literal_eval
objects = ast.literal_eval(command_enumeration.split("\n")[0].split(":")[1].strip())

In [28]:
oqual = command_enumeration.split("\n")[1]
start_index = oqual.find('{')
end_index = oqual.rfind('}')
oqual = ast.literal_eval(oqual[start_index:end_index+1])
oqual


In [32]:
# get manipulation type from command_enumeration as string
manipulation = ast.literal_eval(command_enumeration.split("\n")[2].split(":")[1].strip())
manipulation

'pick'

In [33]:
# get manipulation qualities from command_enumeration as list
mqual = ast.literal_eval(command_enumeration.split("\n")[3].split(":")[1].strip())
mqual

['gently', 'ignore irrelevant options']

In [13]:
object_qualities = ast.literal_eval(command_enumeration.split("\n")[1].split(":")[1].strip())

SyntaxError: '{' was never closed (<unknown>, line 1)

In [56]:
# get object(s) as list from command enumeration, after '1. Objects: ...' and before '2. Object Qualities: ...'
objects_search = re.search(r'1\. Objects:\s*\[(.*?)\]', command_enumeration)
if objects_search:
    objects = [obj.strip() for obj in objects_search.group(1).split(',')]
else:
    objects = []


In [57]:
objects

["'avocados'"]

In [58]:
qualities_match = re.search(r'2\. Object Qualities:\s*({.*?})', command_enumeration)
if qualities_match:
    object_qualities = json.loads(qualities_match.group(1).replace("'", '\"'))
else:
    object_qualities = {}

print("Object Qualities:", object_qualities)


Object Qualities: {'avocados': ['large']}


: 

In [32]:
tc = task_configs.ALL_TASKS['magpie']
tc.prompts['thinker_coder']


magpie.prompt_planner.prompts.mp_prompt_thinker_coder_muk.PromptThinkerCoder

In [6]:
import numpy as np
from PIL import Image
import base64
import io
import cv2 

def encode_image(img):
    # Convert NumPy array to base64 encoded string
    return base64.b64encode(img).decode('utf-8')


i = encode_image(np.array(Image.open("static/favicon.jpg")))

In [7]:
MODEL = "gpt-3.5-turbo"
import dataclasses
from typing import Any

In [8]:
@dataclasses.dataclass(frozen=True)
class TaskConfig:
  client: None
  prompts: dict[str, type[Any]]

ALL_TASKS = {
    'magpie': TaskConfig(
        client=None,
        prompts={
            'thinker_coder': mptc.PromptThinkerCoder,
        },
    ),
}


In [17]:
safe_executor = confirmation_safe_executor.ConfirmationSafeExecutor()
task_config = ALL_TASKS['magpie']
openai.api_key = API_KEY
prompt = task_config.prompts['thinker_coder']
MODEL = "gpt-3.5-turbo"

In [26]:
try:
    prompt_model = prompt(
        None, executor=safe_executor
    )
    conv = conversation.Conversation(prompt_model, MODEL)
    while True:
      user_command = input(termcolor.colored("User: ", "red", attrs=["bold"]))
      try:
        response = conv.send_command(user_command)
        print(termcolor.colored("Magpie: ", "green", attrs=["bold"]) + response + "\n")
      except Exception as e:  # pylint: disable=broad-exception-caught
        print("Planning failed, try something else... " + str(e) + "\n")
        continue
      
      try:
        prompt_model.code_executor(response)
      except Exception as e:  # pylint: disable=broad-exception-caught
        print("Execution failed, try something else... " + str(e) + "\n")

except Exception as e:
    print(e)
    prompt_model = None

LLM0 queried
[start of description]
* This is a new grasp.
* This grasp should be for picking up a grape.
* This is a complete grasp.
* This grasp is for an object with low compliance.
* The object has an approximate mass of 5 grams.
* The object has an approximate spring constant of 50 Newtons per meter.
* The gripper and object have an approximate friction coefficient of 0.2.
* This grasp should set the goal aperture to 5 mm.
* Based on object mass and friction coefficient, grasp should initially set the contact force to 1 Newton.
* If the gripper slips, this grasp should close an additional 1 mm.
* If the gripper slips, this grasp should increase the output force by 0.005 Newtons.
[end of description]

LLM1 queried
```python
from magpie.gripper import Gripper
G = Gripper()

import numpy as np

new_task = True

if new_task:
    G.reset_parameters()

goal_aperture = 5
complete_grasp = True
initial_force = (5 * 9.81) / 0.2
additional_closure = 1
spring_constant = 50
additional_force = 

KeyboardInterrupt: 